app:
  appEnv: "dev"  # develop: dev or staging: stg or production: prd

web:
  host: "localhost"
  port: "8080"

database:
  driver: "sqlite3"
  sourcePath: "data/"
  sourceName: "artist.db"
  username: ""
  password: ""

table:
  music: "music"
  artist: "artist"
  company: "company"

message:
  routeNotFound: "Route Not Found"
  methodNotAllowed: "Method Not Allowed"
  recordNotFound: "Record Not Found"
  saveError: "New Record Save Error"
